// Provisional Neo4j 5 templates; labels requested by the user, semantics external.
// Run only against a caller-selected database after architecture/schema approval.
CREATE CONSTRAINT entity_id IF NOT EXISTS FOR (n:Entity) REQUIRE n.id IS UNIQUE;
CREATE INDEX disease_id IF NOT EXISTS FOR (n:Disease) ON (n.id);
CREATE INDEX drug_id IF NOT EXISTS FOR (n:Drug) ON (n.id);
CREATE INDEX symptom_id IF NOT EXISTS FOR (n:Symptom) ON (n.id);
CREATE INDEX procedure_id IF NOT EXISTS FOR (n:Procedure) ON (n.id);

// Execute each template separately with caller-provided $rows.
UNWIND $rows AS row MERGE (n:Entity:Disease {id: row.id}) SET n += row.properties;
UNWIND $rows AS row MERGE (n:Entity:Drug {id: row.id}) SET n += row.properties;
UNWIND $rows AS row MERGE (n:Entity:Symptom {id: row.id}) SET n += row.properties;
UNWIND $rows AS row MERGE (n:Entity:Procedure {id: row.id}) SET n += row.properties;

// Relationships are generated by graph-plan from a caller-supplied type allowlist.
// No default relations are defined. Values use $rows; only validated type tokens
// are interpolated. No query, index, embedding, or vector database was executed.
