ALTER TABLE accounts ADD COLUMN terms_version INTEGER NOT NULL DEFAULT 0
ALTER TABLE accounts ADD COLUMN terms_at INTEGER NOT NULL DEFAULT 0
ALTER TABLE accounts ADD COLUMN ai_consent INTEGER NOT NULL DEFAULT 0
ALTER TABLE accounts ADD COLUMN ai_consent_at INTEGER NOT NULL DEFAULT 0
ALTER TABLE accounts ADD COLUMN rules_version INTEGER NOT NULL DEFAULT 0
ALTER TABLE accounts ADD COLUMN rules_at INTEGER NOT NULL DEFAULT 0
ALTER TABLE accounts ADD COLUMN share_banned INTEGER NOT NULL DEFAULT 0
ALTER TABLE accounts ADD COLUMN joined_via TEXT
ALTER TABLE accounts ADD COLUMN account_token TEXT
ALTER TABLE accounts ADD COLUMN paid_until INTEGER NOT NULL DEFAULT 0
ALTER TABLE accounts ADD COLUMN referral_code TEXT
ALTER TABLE accounts ADD COLUMN app_transaction_id TEXT
ALTER TABLE accounts ADD COLUMN last_seen_day TEXT
ALTER TABLE accounts ADD COLUMN caps TEXT
