import Foundation

// Two example patients, written for this app: one in the emergency
// department, one in clinic. They show every part of a case (the clerking
// note, both groups of steps, key and low-yield steps, red flags, a
// must-not-miss, results with flags, differentials with the steps for and
// against) and pass the same checks as a written case (CaseChecks; the
// "cases" suite holds them to it).
//
// The medicine follows current UK guidance: NICE NG158 (venous
// thromboembolic diseases, 2020) for the first, the British Society for
// Rheumatology's guideline on giant cell arteritis (2020) for the second.

enum CaseSamples {

    // MARK: 1. emergency: pleuritic pain after a long flight

    static let breathless = CaseFile(
        id: UUID(uuidString: "CA5E0001-0000-4000-8000-000000000001")!,
        title: "Sharp chest pain after a long flight",
        specialty: "Respiratory",
        setting: .emergency,
        patient: CaseFile.Patient(name: "Leah Moreno", age: 34, sex: "F", about: "architect, back from a work trip"),
        complaint: "It hurts on the right when I breathe in, and I can't get my breath since this morning.",
        clerking: CaseFile.Clerking(
            presenting: "Right-sided pleuritic chest pain and breathlessness since this morning.",
            history: "Sudden onset on waking, sharp, worse on deep inspiration, not related to exertion. One streak of bright red blood in her sputum this morning. Dry cough, no fever. Flew home from Sydney 3 days ago (about 22 hours in the air).",
            past: "Nil of note. No previous clots.",
            drugs: "Combined oral contraceptive pill. No known allergies.",
            social: "Architect. Never smoked. Alcohol socially."),
        arrival: [
            .init(sign: .hr, value: 112),
            .init(sign: .bp, value: 118, second: 76),
            .init(sign: .rr, value: 24),
            .init(sign: .spo2, value: 93),
            .init(sign: .temp, value: 37.4),
        ],
        budgetMinutes: 60,
        steps: [
            CaseStep(id: "s1", group: .examine, label: "Inspect the chest",
                     finding: "Fast, shallow breathing; she splints the right side on inspiration; both sides expand equally.",
                     minutes: 2, value: .useful,
                     note: "Splinting fits pleural pain; equal expansion makes a large pneumothorax less likely."),
            CaseStep(id: "s2", group: .examine, label: "Examine the legs",
                     finding: "Right calf 3 cm wider than the left, tender along the deep veins, with pitting oedema.",
                     minutes: 3, value: .key, redFlag: true, mustNotMiss: true,
                     note: "Signs of a deep vein thrombosis make pulmonary embolism the leading diagnosis (Wells score above 4)."),
            CaseStep(id: "s3", group: .examine, label: "Listen to the chest",
                     finding: "Equal air entry, clear breath sounds, normal percussion note on both sides.",
                     minutes: 2, value: .useful,
                     note: "A clear chest argues against pneumonia and a pneumothorax."),
            CaseStep(id: "s4", group: .examine, label: "Check the neck veins and heart",
                     finding: "Jugular venous pressure not raised; normal heart sounds; no rub.",
                     minutes: 2, value: .useful,
                     note: "No rub argues against pericarditis; no raised venous pressure, so no sign of right heart strain."),
            CaseStep(id: "s5", group: .examine, label: "Blood pressure in both arms",
                     finding: "118/76 in both arms.",
                     minutes: 2, value: .low,
                     note: "Nothing in the story suggests aortic dissection, so this adds little here."),
            CaseStep(id: "s6", group: .examine, label: "Look in the throat",
                     finding: "Mildly red pharynx; no exudate.",
                     minutes: 2, value: .low,
                     note: "A sore throat is not part of this story and does not explain pleuritic pain."),
            CaseStep(id: "s7", group: .test, label: "12-lead ECG",
                     finding: "Sinus tachycardia at 112 per minute; no ST elevation.",
                     minutes: 5, value: .useful,
                     note: "No sign of a heart attack or pericarditis; tachycardia fits embolism."),
            CaseStep(id: "s8", group: .test, label: "Arterial blood gas on air",
                     finding: "Low oxygen with a low carbon dioxide: type 1 respiratory failure.",
                     minutes: 10, value: .key, redFlag: true,
                     results: [
                        .init(name: "pH", value: 7.47),
                        .init(name: "PaO2", value: 8.9, unit: "kPa"),
                        .init(name: "PaCO2", value: 4.1, unit: "kPa"),
                     ],
                     note: "Hypoxaemia with hyperventilation and a clear chest points to a perfusion defect."),
            CaseStep(id: "s9", group: .test, label: "Chest X-ray",
                     finding: "Clear lung fields; no consolidation, effusion or pneumothorax.",
                     minutes: 20, value: .useful,
                     note: "A normal film in a breathless, hypoxic patient makes embolism more likely, not less."),
            CaseStep(id: "s10", group: .test, label: "CRP",
                     finding: "Mildly raised.",
                     minutes: 15, value: .useful,
                     results: [.init(name: "CRP", value: 18, unit: "mg/L", low: 0, high: 5)],
                     note: "A mild rise is common in embolism and does not make this pneumonia."),
            CaseStep(id: "s11", group: .test, label: "Troponin",
                     finding: "Slightly raised.",
                     minutes: 15, value: .useful,
                     results: [.init(name: "hs-Troponin T", value: 22, unit: "ng/L", low: 0, high: 14)],
                     note: "A small rise is common in embolism; with no ST change and a normal right ventricle it does not change the plan."),
            CaseStep(id: "s12", group: .test, label: "D-dimer",
                     finding: "Raised.",
                     minutes: 15, value: .low,
                     results: [.init(name: "D-dimer", value: 2.1, unit: "mg/L FEU", low: 0, high: 0.5)],
                     note: "With embolism likely on the Wells score, a D-dimer changes nothing: go straight to imaging."),
            CaseStep(id: "s13", group: .test, label: "CT pulmonary angiogram",
                     finding: "Filling defects in the right lower lobe pulmonary arteries; right ventricle normal in size.",
                     minutes: 30, value: .key,
                     note: "Confirms the embolism and shows no right ventricular strain."),
        ],
        diagnosis: CaseFile.Diagnosis(name: "Pulmonary embolism", accepted: ["PE", "Pulmonary thromboembolism"]),
        differentials: [
            Differential(name: "Pulmonary embolism", accepted: ["PE", "Pulmonary thromboembolism"],
                         supportedBy: ["s2", "s8", "s9", "s13"], againstBy: []),
            Differential(name: "Pneumonia", accepted: ["Community-acquired pneumonia", "Chest infection"],
                         supportedBy: ["s10"], againstBy: ["s3", "s9"]),
            Differential(name: "Pneumothorax", accepted: ["Spontaneous pneumothorax"],
                         supportedBy: ["s1"], againstBy: ["s3", "s9"]),
            Differential(name: "Pericarditis", accepted: ["Acute pericarditis"],
                         supportedBy: ["s11"], againstBy: ["s4", "s7"]),
        ],
        distractors: ["Acute asthma", "Panic attack", "Aortic dissection"],
        turningStep: "s2",
        nextStep: CaseFile.NextStep(
            options: [
                "Start apixaban, a direct oral anticoagulant",
                "Give alteplase for systemic thrombolysis",
                "Insert an inferior vena cava filter today",
                "Start aspirin and arrange outpatient review",
                "Give co-amoxiclav for a chest infection",
            ],
            key: 0,
            why: "She has a confirmed embolism and is haemodynamically stable, so she needs anticoagulation; a direct oral anticoagulant such as apixaban is first line. Thrombolysis is kept for embolism with persistent hypotension."),
        teaching: [
            "Pleuritic pain, breathlessness and a swollen tender calf after a long flight make pulmonary embolism the leading diagnosis.",
            "When embolism is likely on the two-level Wells score, go straight to CT pulmonary angiography; a D-dimer is for when it is unlikely.",
            "Stable embolism is treated with anticoagulation, usually a direct oral anticoagulant; thrombolysis is for embolism with shock.",
        ],
        source: CaseFile.Source(lecture: "Example case", pages: ""),
        verification: .passed)

    // MARK: 2. clinic: a new headache at 72

    static let headache = CaseFile(
        id: UUID(uuidString: "CA5E0002-0000-4000-8000-000000000002")!,
        title: "A new headache at 72",
        specialty: "Rheumatology",
        setting: .clinic,
        patient: CaseFile.Patient(name: "Irene Castell", age: 72, sex: "F", about: "retired librarian, lives with her husband"),
        complaint: "I've had this new headache on the right for three weeks, and it even hurts to brush my hair.",
        clerking: CaseFile.Clerking(
            presenting: "New right-sided headache for 3 weeks.",
            history: "Constant, worse at night; scalp sore when brushing her hair. Jaw aches after a minute of chewing meat and eases on stopping. Two episodes of blurred vision in the right eye this week, each lasting minutes. Stiff, aching shoulders each morning for 2 months. Lost 3 kg; feels feverish in the evenings. Never had headaches before.",
            past: "Hypertension. Osteoarthritis of both knees.",
            drugs: "Amlodipine; paracetamol as needed. No known allergies.",
            social: "Retired librarian, lives with her husband. Never smoked."),
        arrival: [
            .init(sign: .hr, value: 78),
            .init(sign: .bp, value: 142, second: 84),
            .init(sign: .rr, value: 14),
            .init(sign: .spo2, value: 97),
            .init(sign: .temp, value: 37.6),
        ],
        budgetMinutes: 50,
        steps: [
            CaseStep(id: "s1", group: .examine, label: "Feel the temporal arteries",
                     finding: "Right temporal artery thickened, beaded and tender, with no pulse.",
                     minutes: 2, value: .key,
                     note: "An abnormal temporal artery on examination strongly supports giant cell arteritis."),
            CaseStep(id: "s2", group: .examine, label: "Check acuity and fundi",
                     finding: "Acuity 6/12 in the right eye, 6/9 in the left; the right optic disc is pale and swollen.",
                     minutes: 4, value: .key, redFlag: true, mustNotMiss: true,
                     note: "Ischaemic optic neuropathy has begun: the sight in that eye is at risk now, and the other eye can follow."),
            CaseStep(id: "s3", group: .examine, label: "Swinging light test",
                     finding: "A relative afferent pupillary defect on the right.",
                     minutes: 2, value: .useful,
                     note: "Confirms the right optic nerve is affected."),
            CaseStep(id: "s4", group: .examine, label: "Feel the scalp",
                     finding: "Tender over the right temple and parietal scalp.",
                     minutes: 1, value: .useful,
                     note: "Scalp tenderness is common in giant cell arteritis."),
            CaseStep(id: "s5", group: .examine, label: "Move the shoulders and hips",
                     finding: "Painful, stiff active movement at both shoulders; passive movement better; strength normal.",
                     minutes: 3, value: .useful,
                     note: "Polymyalgia often comes with giant cell arteritis."),
            CaseStep(id: "s6", group: .examine, label: "Neurological examination",
                     finding: "No focal neurological signs; no neck stiffness.",
                     minutes: 4, value: .useful,
                     note: "Argues against a stroke, a mass or meningitis."),
            CaseStep(id: "s7", group: .examine, label: "Look in the ears",
                     finding: "Normal ear canals and eardrums.",
                     minutes: 2, value: .low,
                     note: "An ear problem does not cause jaw claudication or scalp tenderness."),
            CaseStep(id: "s8", group: .test, label: "ESR",
                     finding: "Markedly raised.",
                     minutes: 15, value: .key,
                     results: [.init(name: "ESR", value: 88, unit: "mm/h", low: 0, high: 30)],
                     note: "A high ESR supports the diagnosis; a normal one makes it less likely but does not exclude it."),
            CaseStep(id: "s9", group: .test, label: "CRP",
                     finding: "Raised.",
                     minutes: 15, value: .useful,
                     results: [.init(name: "CRP", value: 64, unit: "mg/L", low: 0, high: 5)],
                     note: "Inflammatory markers are raised in almost every case."),
            CaseStep(id: "s10", group: .test, label: "Full blood count",
                     finding: "Mild normocytic anaemia; platelets raised.",
                     minutes: 15, value: .useful,
                     results: [
                        .init(name: "Haemoglobin", value: 11.2, unit: "g/dL"),
                        .init(name: "Platelets", value: 452, unit: "\u{00D7}10\u{2079}/L", low: 150, high: 400),
                     ],
                     note: "Anaemia of inflammation and a reactive thrombocytosis are common."),
            CaseStep(id: "s11", group: .test, label: "Temporal artery ultrasound",
                     finding: "A halo around the right temporal artery that does not compress.",
                     minutes: 20, value: .useful,
                     note: "The halo sign supports the diagnosis; it stays visible for the first days of steroids, so it never delays them."),
            CaseStep(id: "s12", group: .test, label: "CT head",
                     finding: "No intracranial abnormality.",
                     minutes: 30, value: .low,
                     note: "A brain scan does not look at the inflamed arteries, and waiting for it delays treatment."),
            CaseStep(id: "s13", group: .test, label: "Urine dipstick",
                     finding: "Normal.",
                     minutes: 5, value: .low,
                     note: "Nothing in the story points to the kidneys."),
        ],
        diagnosis: CaseFile.Diagnosis(name: "Giant cell arteritis", accepted: ["Temporal arteritis", "GCA"]),
        differentials: [
            Differential(name: "Giant cell arteritis", accepted: ["Temporal arteritis", "GCA"],
                         supportedBy: ["s1", "s2", "s4", "s8", "s11"], againstBy: []),
            Differential(name: "Polymyalgia rheumatica", accepted: ["PMR"],
                         supportedBy: ["s5", "s8"], againstBy: ["s1", "s2", "s11"]),
            Differential(name: "Tension-type headache", accepted: ["Tension headache"],
                         supportedBy: ["s4"], againstBy: ["s1", "s8", "s11"]),
        ],
        distractors: ["Trigeminal neuralgia", "Acute angle-closure glaucoma", "Sinusitis"],
        turningStep: "s1",
        nextStep: CaseFile.NextStep(
            options: [
                "Start high-dose steroids today, before a biopsy",
                "Arrange a temporal artery biopsy, then treat",
                "Prescribe sumatriptan and review in a week",
                "Request an MRI brain and wait for the result",
                "Start amitriptyline at night for the pain",
            ],
            key: 0,
            why: "Treatment starts on suspicion, the same day, because sight is already threatened; with visual loss the guideline advises intravenous methylprednisolone and same-day eye and rheumatology review. A biopsy or ultrasound still confirms the diagnosis in the first one to two weeks of steroids."),
        teaching: [
            "A new headache after 50 with jaw claudication or scalp tenderness is giant cell arteritis until proven otherwise.",
            "Visual symptoms, and a pale swollen optic disc above all, make treatment an emergency: steroids start the same day.",
            "Never wait for a biopsy or ultrasound to treat; both stay informative in the first one to two weeks of steroids.",
        ],
        source: CaseFile.Source(lecture: "Example case", pages: ""),
        verification: .passed)

    static let all: [CaseFile] = [breathless, headache]
}
