// Generated by tools/icon_layers.py from the same numbers as design/icon/layers
// and AppIcon.icon - edit the script and run it, not this file.
#if canImport(SwiftUI)
import SwiftUI

/// The app icon drawn in the app, layer by layer, on Icon Composer's
/// 1024-point canvas scaled to fit: `IconLayersView()` is the whole icon, and
/// `IconLayerView(layer:)` one layer, so a screen can move or light them apart.
struct IconLayersView: View {
    var layers: [IconLayer] = IconLayer.allCases
    var body: some View {
        ZStack { ForEach(layers, id: \.self) { IconLayerView(layer: $0) } }
            .aspectRatio(1, contentMode: .fit)
            .clipShape(IconTile())
    }
}

/// The rounded tile iOS cuts every icon to.
struct IconTile: Shape {
    func path(in r: CGRect) -> Path {
        RoundedRectangle(cornerRadius: 0.2237 * min(r.width, r.height), style: .continuous).path(in: r)
    }
}

struct IconLayerView: View {
    let layer: IconLayer
    var body: some View {
        Canvas { ctx, size in
            var c = ctx
            c.scaleBy(x: size.width / 1024, y: size.height / 1024)
            IconLayerArt.draw(layer, in: c)
        }
        .aspectRatio(1, contentMode: .fit)
        .accessibilityHidden(true)
    }
}

private enum IconLayerArt {
    static func draw(_ layer: IconLayer, in c: GraphicsContext) {
        switch layer {
        case .background:
            c.fill(Path(CGRect(x: 0, y: 0, width: 1024, height: 1024)), with: lin(P(330, 0), P(694, 1024), [(0x5BBDF9, 0), (0x2C84EE, 0.45), (0x1849D4, 1)]))
        case .metal:
            c.stroke(Path { p in p.move(to: P(300, 128)); p.addCurve(to: P(172, 225), control1: P(240, 118), control2: P(178, 140)); p.addLine(to: P(190, 400)) }, with: .color(hex(0x7B818D)), style: line(26))
            c.stroke(Path { p in p.move(to: P(300, 128)); p.addCurve(to: P(172, 225), control1: P(240, 118), control2: P(178, 140)); p.addLine(to: P(190, 400)) }, with: .color(hex(0xD3D6DC)), style: line(16))
            c.stroke(Path { p in p.move(to: P(466, 152)); p.addCurve(to: P(546, 266), control1: P(530, 150), control2: P(566, 205)); p.addLine(to: P(440, 436)) }, with: .color(hex(0x7B818D)), style: line(26))
            c.stroke(Path { p in p.move(to: P(466, 152)); p.addCurve(to: P(546, 266), control1: P(530, 150), control2: P(566, 205)); p.addLine(to: P(440, 436)) }, with: .color(hex(0xD3D6DC)), style: line(16))
            c.stroke(Path { p in p.move(to: P(768, 590)); p.addLine(to: P(759, 648)) }, with: .color(hex(0x7B818D)), style: line(34))
            c.stroke(Path { p in p.move(to: P(768, 590)); p.addLine(to: P(759, 648)) }, with: .color(hex(0xD3D6DC)), style: line(24))
        case .tubing:
            c.stroke(Path { p in p.move(to: P(268, 560)); p.addCurve(to: P(300, 800), control1: P(238, 620), control2: P(238, 740)); p.addCurve(to: P(560, 900), control1: P(360, 860), control2: P(470, 905)); p.addCurve(to: P(742, 760), control1: P(660, 893), control2: P(720, 830)); p.addLine(to: P(760, 648)) }, with: .color(hex(0x07307A)), style: line(48))
            c.stroke(Path { p in p.move(to: P(190, 392)); p.addCurve(to: P(268, 560), control1: P(186, 480), control2: P(205, 545)) }, with: .color(hex(0x07307A)), style: line(48))
            c.stroke(Path { p in p.move(to: P(442, 428)); p.addCurve(to: P(268, 560), control1: P(400, 500), control2: P(345, 548)) }, with: .color(hex(0x07307A)), style: line(48))
            c.stroke(Path { p in p.move(to: P(268, 560)); p.addCurve(to: P(300, 800), control1: P(238, 620), control2: P(238, 740)); p.addCurve(to: P(560, 900), control1: P(360, 860), control2: P(470, 905)); p.addCurve(to: P(742, 760), control1: P(660, 893), control2: P(720, 830)); p.addLine(to: P(760, 648)) }, with: .color(hex(0x0E49AE)), style: line(36))
            c.stroke(Path { p in p.move(to: P(190, 392)); p.addCurve(to: P(268, 560), control1: P(186, 480), control2: P(205, 545)) }, with: .color(hex(0x0E49AE)), style: line(36))
            c.stroke(Path { p in p.move(to: P(442, 428)); p.addCurve(to: P(268, 560), control1: P(400, 500), control2: P(345, 548)) }, with: .color(hex(0x0E49AE)), style: line(36))
            c.stroke(Path { p in p.move(to: P(608, 720)); p.addCurve(to: P(488, 840), control1: P(608, 786.28), control2: P(554.28, 840)); p.addCurve(to: P(368, 720), control1: P(421.72, 840), control2: P(368, 786.28)); p.addCurve(to: P(488, 600), control1: P(368, 653.72), control2: P(421.72, 600)); p.addCurve(to: P(608, 720), control1: P(554.28, 600), control2: P(608, 653.72)) }, with: .color(hex(0x07307A)), style: line(48))
            c.stroke(Path { p in p.move(to: P(608, 720)); p.addCurve(to: P(488, 840), control1: P(608, 786.28), control2: P(554.28, 840)); p.addCurve(to: P(368, 720), control1: P(421.72, 840), control2: P(368, 786.28)); p.addCurve(to: P(488, 600), control1: P(368, 653.72), control2: P(421.72, 600)); p.addCurve(to: P(608, 720), control1: P(554.28, 600), control2: P(608, 653.72)) }, with: .color(hex(0x0E49AE)), style: line(36))
        case .earpieces:
            c.fill(oval(316, 138, 40, 32, degrees: -5), with: lin(P(0, 105), P(0, 185), [(0xFFFFFF, 0), (0xD6D8DD, 1)]))
            c.fill(oval(452, 152, 40, 32, degrees: 8), with: lin(P(0, 105), P(0, 185), [(0xFFFFFF, 0), (0xD6D8DD, 1)]))
        case .chestPiece:
            c.fill(Path(ellipseIn: CGRect(x: 658, y: 346, width: 264, height: 264)), with: lin(P(690, 358), P(890, 598), [(0xF4F5F7, 0), (0xB9BDC6, 0.55), (0x7D838F, 1)]))
            c.fill(Path(ellipseIn: CGRect(x: 674, y: 362, width: 232, height: 232)), with: .color(hex(0x4A4E58)))
            c.fill(Path(ellipseIn: CGRect(x: 688, y: 376, width: 204, height: 204)), with: lin(P(870, 568), P(710, 388), [(0xC4C8CF, 0), (0xF6F6F8, 1)]))
            c.fill(Path(ellipseIn: CGRect(x: 702, y: 390, width: 176, height: 176)), with: lin(P(730, 398), P(850, 558), [(0xFAFAFB, 0), (0xD3D5DA, 1)]))
        case .aPlus:
            c.fill(Path { p in p.move(to: P(734, 521)); p.addLine(to: P(765, 428)); p.addLine(to: P(795, 428)); p.addLine(to: P(826, 521)); p.addLine(to: P(801, 521)); p.addLine(to: P(794, 500)); p.addLine(to: P(766, 500)); p.addLine(to: P(759, 521)); p.closeSubpath(); p.move(to: P(772, 478)); p.addLine(to: P(788, 478)); p.addLine(to: P(780, 451)); p.closeSubpath() }, with: .color(hex(0x0E3C8C)), style: FillStyle(eoFill: true))
            c.fill(Path { p in p.move(to: P(844, 446)); p.addLine(to: P(860, 446)); p.addLine(to: P(860, 460)); p.addLine(to: P(874, 460)); p.addLine(to: P(874, 476)); p.addLine(to: P(860, 476)); p.addLine(to: P(860, 490)); p.addLine(to: P(844, 490)); p.addLine(to: P(844, 476)); p.addLine(to: P(830, 476)); p.addLine(to: P(830, 460)); p.addLine(to: P(844, 460)); p.closeSubpath() }, with: .color(hex(0x0E3C8C)), style: FillStyle(eoFill: true))
        }
    }
    private static func P(_ x: CGFloat, _ y: CGFloat) -> CGPoint { CGPoint(x: x, y: y) }
    private static func hex(_ v: UInt32) -> Color {
        Color(red: Double(v >> 16 & 0xFF) / 255, green: Double(v >> 8 & 0xFF) / 255, blue: Double(v & 0xFF) / 255)
    }
    private static func lin(_ a: CGPoint, _ b: CGPoint, _ stops: [(UInt32, Double)]) -> GraphicsContext.Shading {
        .linearGradient(Gradient(stops: stops.map { .init(color: hex($0.0), location: $0.1) }), startPoint: a, endPoint: b)
    }
    private static func line(_ w: CGFloat) -> StrokeStyle { StrokeStyle(lineWidth: w, lineCap: .round, lineJoin: .round) }
    private static func oval(_ x: CGFloat, _ y: CGFloat, _ rx: CGFloat, _ ry: CGFloat, degrees: Double) -> Path {
        Path(ellipseIn: CGRect(x: -rx, y: -ry, width: 2 * rx, height: 2 * ry))
            .applying(CGAffineTransform(rotationAngle: degrees * .pi / 180).concatenating(CGAffineTransform(translationX: x, y: y)))
    }
}
#endif
